### ISSUE TITLE
Generating Sbox tables

### ISSUE THREAD

**Issue by ghost** [mjosaarinen/kuznechik#1]
In paper by Alex Biryukov, Leo Perrin, and Aleksei Udovenko "Reverse-Engineering the S-Box of Streebog, Kuznyechik and STRIBOBr1" is some python code in appendix that uses safe to generate sbox tables.

https://github.com/picarresursix/GOST-pi

Could you implement this for your next version as an compile option?

**Comment by mjosaarinen** [comment]
Hi,

How would that be useful ?

Cheers,
- markku

Dr. Markku-Juhani O. Saarinen mjos@iki.fi

**Comment by ghost** [comment]
Useful to optimize code for size?
Would be educational if nothing else. 
I see that sage can export scripts to C here http://ask.sagemath.org/question/7922/export-to-c-code/ but I don't have it installed.

**Comment by ghost** [comment]
Hi again,

Aleksei sent me some code which is attached if interested.
thanks!
[genpi.c.txt](https://github.com/mjosaarinen/kuznechik/files/267019/genpi.c.txt)
